# Generated by Django 5.2.11 on 2026-03-04 08:02

import django.db.models.deletion
import hosting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='网址标识')),
                ('description', models.TextField(blank=True, verbose_name='网站描述')),
                ('upload_file', models.FileField(upload_to=hosting.models.website_upload_path, verbose_name='上传文件')),
                ('site_path', models.CharField(blank=True, max_length=500, verbose_name='网站路径')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('offline', '已下线')], default='draft', max_length=20, verbose_name='状态')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('guest', '游客'), ('user', '普通用户'), ('admin', '管理员')], default='guest', max_length=20, verbose_name='权限级别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置文件',
                'verbose_name_plural': '用户配置文件',
            },
        ),
    ]
