# Generated by Django 5.2.11 on 2026-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access',
            field=models.BooleanField(default=True, verbose_name='可以访问网站'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='可以删除网站'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='可以编辑网站信息'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_upload',
            field=models.BooleanField(default=False, verbose_name='可以上传网站'),
        ),
    ]
