# Generated by Django 5.2.11 on 2026-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_website_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permission_level',
            field=models.CharField(choices=[('guest', '游客'), ('user', '普通用户'), ('admin', '管理员'), ('superadmin', '超级管理员')], default='guest', max_length=20, verbose_name='权限级别'),
        ),
    ]
