# Generated by Django 5.2.11 on 2026-03-06 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_alter_userprofile_permission_level_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('permission_level', models.CharField(blank=True, max_length=20, verbose_name='权限级别')),
                ('can_upload', models.BooleanField(blank=True, null=True, verbose_name='可以上传网站')),
                ('can_edit', models.BooleanField(blank=True, null=True, verbose_name='可以编辑网站信息')),
                ('can_access', models.BooleanField(blank=True, null=True, verbose_name='可以访问网站')),
                ('can_delete', models.BooleanField(blank=True, null=True, verbose_name='可以删除网站')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_logs', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '权限变更日志',
                'verbose_name_plural': '权限变更日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
